// All phone codes available for independent selection
export const phoneCodes = [
  { code: "+1", label: "+1 (USA, Canada)" },
  { code: "+7", label: "+7 (Russia, Kazakhstan)" },
  { code: "+20", label: "+20 (Egypt)" },
  { code: "+27", label: "+27 (South Africa)" },
  { code: "+30", label: "+30 (Greece)" },
  { code: "+31", label: "+31 (Netherlands)" },
  { code: "+32", label: "+32 (Belgium)" },
  { code: "+33", label: "+33 (France)" },
  { code: "+34", label: "+34 (Spain)" },
  { code: "+36", label: "+36 (Hungary)" },
  { code: "+39", label: "+39 (Italy)" },
  { code: "+40", label: "+40 (Romania)" },
  { code: "+41", label: "+41 (Switzerland)" },
  { code: "+43", label: "+43 (Austria)" },
  { code: "+44", label: "+44 (United Kingdom)" },
  { code: "+45", label: "+45 (Denmark)" },
  { code: "+46", label: "+46 (Sweden)" },
  { code: "+47", label: "+47 (Norway)" },
  { code: "+48", label: "+48 (Poland)" },
  { code: "+49", label: "+49 (Germany)" },
  { code: "+51", label: "+51 (Peru)" },
  { code: "+52", label: "+52 (Mexico)" },
  { code: "+53", label: "+53 (Cuba)" },
  { code: "+54", label: "+54 (Argentina)" },
  { code: "+55", label: "+55 (Brazil)" },
  { code: "+56", label: "+56 (Chile)" },
  { code: "+57", label: "+57 (Colombia)" },
  { code: "+58", label: "+58 (Venezuela)" },
  { code: "+60", label: "+60 (Malaysia)" },
  { code: "+61", label: "+61 (Australia)" },
  { code: "+62", label: "+62 (Indonesia)" },
  { code: "+63", label: "+63 (Philippines)" },
  { code: "+64", label: "+64 (New Zealand)" },
  { code: "+65", label: "+65 (Singapore)" },
  { code: "+66", label: "+66 (Thailand)" },
  { code: "+81", label: "+81 (Japan)" },
  { code: "+82", label: "+82 (South Korea)" },
  { code: "+84", label: "+84 (Vietnam)" },
  { code: "+86", label: "+86 (China)" },
  { code: "+90", label: "+90 (Turkey)" },
  { code: "+91", label: "+91 (India)" },
  { code: "+92", label: "+92 (Pakistan)" },
  { code: "+93", label: "+93 (Afghanistan)" },
  { code: "+94", label: "+94 (Sri Lanka)" },
  { code: "+95", label: "+95 (Myanmar)" },
  { code: "+98", label: "+98 (Iran)" },
  { code: "+212", label: "+212 (Morocco)" },
  { code: "+213", label: "+213 (Algeria)" },
  { code: "+216", label: "+216 (Tunisia)" },
  { code: "+218", label: "+218 (Libya)" },
  { code: "+220", label: "+220 (Gambia)" },
  { code: "+221", label: "+221 (Senegal)" },
  { code: "+223", label: "+223 (Mali)" },
  { code: "+224", label: "+224 (Guinea)" },
  { code: "+225", label: "+225 (Ivory Coast)" },
  { code: "+226", label: "+226 (Burkina Faso)" },
  { code: "+227", label: "+227 (Niger)" },
  { code: "+228", label: "+228 (Togo)" },
  { code: "+229", label: "+229 (Benin)" },
  { code: "+230", label: "+230 (Mauritius)" },
  { code: "+231", label: "+231 (Liberia)" },
  { code: "+232", label: "+232 (Sierra Leone)" },
  { code: "+233", label: "+233 (Ghana)" },
  { code: "+234", label: "+234 (Nigeria)" },
  { code: "+235", label: "+235 (Chad)" },
  { code: "+236", label: "+236 (Central African Republic)" },
  { code: "+237", label: "+237 (Cameroon)" },
  { code: "+238", label: "+238 (Cape Verde)" },
  { code: "+240", label: "+240 (Equatorial Guinea)" },
  { code: "+241", label: "+241 (Gabon)" },
  { code: "+242", label: "+242 (Republic of the Congo)" },
  { code: "+243", label: "+243 (DR Congo)" },
  { code: "+244", label: "+244 (Angola)" },
  { code: "+245", label: "+245 (Guinea-Bissau)" },
  { code: "+248", label: "+248 (Seychelles)" },
  { code: "+249", label: "+249 (Sudan)" },
  { code: "+250", label: "+250 (Rwanda)" },
  { code: "+251", label: "+251 (Ethiopia)" },
  { code: "+252", label: "+252 (Somalia)" },
  { code: "+253", label: "+253 (Djibouti)" },
  { code: "+254", label: "+254 (Kenya)" },
  { code: "+255", label: "+255 (Tanzania)" },
  { code: "+256", label: "+256 (Uganda)" },
  { code: "+257", label: "+257 (Burundi)" },
  { code: "+258", label: "+258 (Mozambique)" },
  { code: "+260", label: "+260 (Zambia)" },
  { code: "+261", label: "+261 (Madagascar)" },
  { code: "+263", label: "+263 (Zimbabwe)" },
  { code: "+264", label: "+264 (Namibia)" },
  { code: "+265", label: "+265 (Malawi)" },
  { code: "+266", label: "+266 (Lesotho)" },
  { code: "+267", label: "+267 (Botswana)" },
  { code: "+268", label: "+268 (Eswatini)" },
  { code: "+350", label: "+350 (Gibraltar)" },
  { code: "+351", label: "+351 (Portugal)" },
  { code: "+352", label: "+352 (Luxembourg)" },
  { code: "+353", label: "+353 (Ireland)" },
  { code: "+354", label: "+354 (Iceland)" },
  { code: "+355", label: "+355 (Albania)" },
  { code: "+356", label: "+356 (Malta)" },
  { code: "+357", label: "+357 (Cyprus)" },
  { code: "+358", label: "+358 (Finland)" },
  { code: "+359", label: "+359 (Bulgaria)" },
  { code: "+370", label: "+370 (Lithuania)" },
  { code: "+371", label: "+371 (Latvia)" },
  { code: "+372", label: "+372 (Estonia)" },
  { code: "+373", label: "+373 (Moldova)" },
  { code: "+374", label: "+374 (Armenia)" },
  { code: "+375", label: "+375 (Belarus)" },
  { code: "+376", label: "+376 (Andorra)" },
  { code: "+377", label: "+377 (Monaco)" },
  { code: "+378", label: "+378 (San Marino)" },
  { code: "+380", label: "+380 (Ukraine)" },
  { code: "+381", label: "+381 (Serbia)" },
  { code: "+382", label: "+382 (Montenegro)" },
  { code: "+383", label: "+383 (Kosovo)" },
  { code: "+385", label: "+385 (Croatia)" },
  { code: "+386", label: "+386 (Slovenia)" },
  { code: "+387", label: "+387 (Bosnia)" },
  { code: "+389", label: "+389 (North Macedonia)" },
  { code: "+420", label: "+420 (Czech Republic)" },
  { code: "+421", label: "+421 (Slovakia)" },
  { code: "+423", label: "+423 (Liechtenstein)" },
  { code: "+971", label: "+971 (UAE)" },
  { code: "+972", label: "+972 (Israel)" },
  { code: "+973", label: "+973 (Bahrain)" },
  { code: "+974", label: "+974 (Qatar)" },
  { code: "+975", label: "+975 (Bhutan)" },
  { code: "+976", label: "+976 (Mongolia)" },
  { code: "+977", label: "+977 (Nepal)" }
];

// Comprehensive list of all world countries with states/provinces
export const countries = [
  { name: "Afghanistan", code: "AF", phoneCode: "+93", states: ["Kabul", "Kandahar", "Herat", "Balkh", "Nangarhar", "Helmand", "Ghazni"] },
  { name: "Albania", code: "AL", phoneCode: "+355", states: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan", "Korçë", "Fier", "Berat"] },
  { name: "Algeria", code: "DZ", phoneCode: "+213", states: ["Algiers", "Oran", "Constantine", "Batna", "Sétif", "Annaba", "Blida", "Djelfa"] },
  { name: "Andorra", code: "AD", phoneCode: "+376", states: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana", "Canillo", "Ordino", "Sant Julià de Lòria"] },
  { name: "Angola", code: "AO", phoneCode: "+244", states: ["Luanda", "Huambo", "Benguela", "Lobito", "Cabinda", "Lubango"] },
  { name: "Antigua and Barbuda", code: "AG", phoneCode: "+1-268", states: ["Saint John's", "All Saints", "Liberta", "Potter's Village"] },
  { name: "Argentina", code: "AR", phoneCode: "+54", states: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Salta", "Entre Ríos", "Misiones"] },
  { name: "Armenia", code: "AM", phoneCode: "+374", states: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan"] },
  { name: "Australia", code: "AU", phoneCode: "+61", states: ["New South Wales", "Victoria", "Queensland", "South Australia", "Western Australia", "Tasmania", "Northern Territory", "Australian Capital Territory"] },
  { name: "Austria", code: "AT", phoneCode: "+43", states: ["Vienna", "Lower Austria", "Upper Austria", "Styria", "Tyrol", "Carinthia", "Salzburg", "Vorarlberg", "Burgenland"] },
  { name: "Azerbaijan", code: "AZ", phoneCode: "+994", states: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Nakhchivan"] },
  { name: "Bahamas", code: "BS", phoneCode: "+1-242", states: ["Nassau", "Freeport", "West Grand Bahama", "Coopers Town", "Marsh Harbour"] },
  { name: "Bahrain", code: "BH", phoneCode: "+973", states: ["Manama", "Muharraq", "Riffa", "Hamad Town", "Isa Town"] },
  { name: "Bangladesh", code: "BD", phoneCode: "+880", states: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barisal", "Rangpur", "Mymensingh"] },
  { name: "Barbados", code: "BB", phoneCode: "+1-246", states: ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Bathsheba"] },
  { name: "Belarus", code: "BY", phoneCode: "+375", states: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"] },
  { name: "Belgium", code: "BE", phoneCode: "+32", states: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons"] },
  { name: "Belize", code: "BZ", phoneCode: "+501", states: ["Belize City", "San Ignacio", "Orange Walk", "Belmopan", "Dangriga", "Corozal"] },
  { name: "Benin", code: "BJ", phoneCode: "+229", states: ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Abomey-Calavi", "Bohicon"] },
  { name: "Bhutan", code: "BT", phoneCode: "+975", states: ["Thimphu", "Paro", "Punakha", "Wangdue Phodrang", "Bumthang", "Trashigang"] },
  { name: "Bolivia", code: "BO", phoneCode: "+591", states: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro", "Potosí", "Tarija", "Trinidad"] },
  { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387", states: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina"] },
  { name: "Botswana", code: "BW", phoneCode: "+267", states: ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe", "Selibe Phikwe"] },
  { name: "Brazil", code: "BR", phoneCode: "+55", states: ["São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Paraná", "Rio Grande do Sul", "Pernambuco", "Ceará", "Pará", "Santa Catarina", "Goiás", "Maranhão", "Espírito Santo"] },
  { name: "Brunei", code: "BN", phoneCode: "+673", states: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar"] },
  { name: "Bulgaria", code: "BG", phoneCode: "+359", states: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven"] },
  { name: "Burkina Faso", code: "BF", phoneCode: "+226", states: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Dédougou"] },
  { name: "Burundi", code: "BI", phoneCode: "+257", states: ["Bujumbura", "Gitega", "Muyinga", "Ngozi", "Ruyigi", "Bururi"] },
  { name: "Cambodia", code: "KH", phoneCode: "+855", states: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham", "Prey Veng"] },
  { name: "Cameroon", code: "CM", phoneCode: "+237", states: ["Yaoundé", "Douala", "Garoua", "Bamenda", "Bafoussam", "Maroua", "Ngaoundéré"] },
  { name: "Canada", code: "CA", phoneCode: "+1", states: ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia", "New Brunswick", "Newfoundland and Labrador", "Prince Edward Island", "Northwest Territories", "Yukon", "Nunavut"] },
  { name: "Cape Verde", code: "CV", phoneCode: "+238", states: ["Praia", "Mindelo", "Santa Maria", "Assomada", "Pedra Badejo"] },
  { name: "Central African Republic", code: "CF", phoneCode: "+236", states: ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar"] },
  { name: "Chad", code: "TD", phoneCode: "+235", states: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Koumra"] },
  { name: "Chile", code: "CL", phoneCode: "+56", states: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Iquique"] },
  { name: "China", code: "CN", phoneCode: "+86", states: ["Beijing", "Shanghai", "Guangdong", "Zhejiang", "Jiangsu", "Shandong", "Henan", "Sichuan", "Hubei", "Hunan", "Hebei", "Fujian", "Shaanxi", "Yunnan", "Guangxi", "Jiangxi"] },
  { name: "Colombia", code: "CO", phoneCode: "+57", states: ["Bogotá", "Antioquia", "Valle del Cauca", "Atlántico", "Santander", "Bolívar", "Cundinamarca", "Norte de Santander"] },
  { name: "Comoros", code: "KM", phoneCode: "+269", states: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Mitsamiouli"] },
  { name: "Congo (DRC)", code: "CD", phoneCode: "+243", states: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Goma", "Bukavu"] },
  { name: "Congo (Republic)", code: "CG", phoneCode: "+242", states: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando"] },
  { name: "Costa Rica", code: "CR", phoneCode: "+506", states: ["San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón"] },
  { name: "Croatia", code: "HR", phoneCode: "+385", states: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula"] },
  { name: "Cuba", code: "CU", phoneCode: "+53", states: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Bayamo"] },
  { name: "Cyprus", code: "CY", phoneCode: "+357", states: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia"] },
  { name: "Czech Republic", code: "CZ", phoneCode: "+420", states: ["Prague", "South Moravian", "Moravian-Silesian", "Central Bohemian", "Ústí nad Labem", "Plzeň"] },
  { name: "Denmark", code: "DK", phoneCode: "+45", states: ["Capital Region", "Central Denmark", "North Denmark", "Zealand", "Southern Denmark"] },
  { name: "Djibouti", code: "DJ", phoneCode: "+253", states: ["Djibouti City", "Ali Sabieh", "Dikhil", "Tadjourah", "Obock", "Arta"] },
  { name: "Dominica", code: "DM", phoneCode: "+1-767", states: ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut"] },
  { name: "Dominican Republic", code: "DO", phoneCode: "+1-809", states: ["Santo Domingo", "Santiago", "San Cristóbal", "La Romana", "San Pedro de Macorís", "La Vega"] },
  { name: "Ecuador", code: "EC", phoneCode: "+593", states: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Manta", "Portoviejo"] },
  { name: "Egypt", code: "EG", phoneCode: "+20", states: ["Cairo", "Alexandria", "Giza", "Qalyubia", "Port Said", "Suez", "Luxor", "Aswan", "Asyut", "Beheira", "Beni Suef", "Dakahlia", "Damietta", "Faiyum", "Gharbia", "Ismailia", "Kafr El Sheikh", "Matruh", "Minya", "Monufia", "New Valley", "North Sinai", "Qena", "Red Sea", "Sharqia", "Sohag", "South Sinai"] },
  { name: "El Salvador", code: "SV", phoneCode: "+503", states: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Santa Tecla", "Mejicanos"] },
  { name: "Equatorial Guinea", code: "GQ", phoneCode: "+240", states: ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Mongomo"] },
  { name: "Eritrea", code: "ER", phoneCode: "+291", states: ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu"] },
  { name: "Estonia", code: "EE", phoneCode: "+372", states: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi"] },
  { name: "Eswatini", code: "SZ", phoneCode: "+268", states: ["Mbabane", "Manzini", "Lobamba", "Big Bend", "Malkerns", "Nhlangano"] },
  { name: "Ethiopia", code: "ET", phoneCode: "+251", states: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar", "Hawassa", "Jimma", "Adama"] },
  { name: "Fiji", code: "FJ", phoneCode: "+679", states: ["Suva", "Lautoka", "Nadi", "Labasa", "Ba", "Sigatoka"] },
  { name: "Finland", code: "FI", phoneCode: "+358", states: ["Uusimaa", "Pirkanmaa", "Varsinais-Suomi", "Pohjois-Pohjanmaa", "Keski-Suomi", "Pohjois-Savo"] },
  { name: "France", code: "FR", phoneCode: "+33", states: ["Île-de-France", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie", "Hauts-de-France", "Provence-Alpes-Côte d'Azur", "Grand Est", "Pays de la Loire", "Brittany", "Normandy", "Bourgogne-Franche-Comté", "Centre-Val de Loire", "Corsica"] },
  { name: "Gabon", code: "GA", phoneCode: "+241", states: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila"] },
  { name: "Gambia", code: "GM", phoneCode: "+220", states: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin"] },
  { name: "Georgia", code: "GE", phoneCode: "+995", states: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi", "Gori"] },
  { name: "Germany", code: "DE", phoneCode: "+49", states: ["Bavaria", "Baden-Württemberg", "North Rhine-Westphalia", "Hesse", "Saxony", "Rhineland-Palatinate", "Lower Saxony", "Berlin", "Hamburg", "Bremen", "Schleswig-Holstein", "Brandenburg", "Saxony-Anhalt", "Thuringia", "Mecklenburg-Vorpommern", "Saarland"] },
  { name: "Ghana", code: "GH", phoneCode: "+233", states: ["Greater Accra", "Ashanti", "Western", "Eastern", "Central", "Northern", "Volta", "Upper East", "Upper West", "Brong-Ahafo"] },
  { name: "Greece", code: "GR", phoneCode: "+30", states: ["Attica", "Central Macedonia", "Thessaly", "Crete", "Western Greece", "Peloponnese", "Epirus", "Ionian Islands"] },
  { name: "Grenada", code: "GD", phoneCode: "+1-473", states: ["Saint George's", "Gouyave", "Grenville", "Victoria", "Sauteurs"] },
  { name: "Guatemala", code: "GT", phoneCode: "+502", states: ["Guatemala", "Quetzaltenango", "Escuintla", "Mixco", "Villa Nueva", "Petapa"] },
  { name: "Guinea", code: "GN", phoneCode: "+224", states: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou"] },
  { name: "Guinea-Bissau", code: "GW", phoneCode: "+245", states: ["Bissau", "Bafatá", "Gabú", "Bissora", "Bolama"] },
  { name: "Guyana", code: "GY", phoneCode: "+592", states: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica"] },
  { name: "Haiti", code: "HT", phoneCode: "+509", states: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes", "Jacmel", "Port-de-Paix"] },
  { name: "Honduras", code: "HN", phoneCode: "+504", states: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "El Progreso", "Choluteca"] },
  { name: "Hungary", code: "HU", phoneCode: "+36", states: ["Budapest", "Pest", "Borsod-Abaúj-Zemplén", "Hajdú-Bihar", "Győr-Moson-Sopron", "Bács-Kiskun"] },
  { name: "Iceland", code: "IS", phoneCode: "+354", states: ["Capital Region", "Southern Peninsula", "Western Region", "Westfjords", "Northwest", "Northeast", "East", "South"] },
  { name: "India", code: "IN", phoneCode: "+91", states: ["Maharashtra", "Uttar Pradesh", "Karnataka", "Tamil Nadu", "West Bengal", "Gujarat", "Rajasthan", "Kerala", "Madhya Pradesh", "Punjab", "Delhi", "Andhra Pradesh", "Telangana", "Bihar", "Haryana", "Assam", "Odisha", "Jharkhand", "Chhattisgarh", "Uttarakhand", "Himachal Pradesh"] },
  { name: "Indonesia", code: "ID", phoneCode: "+62", states: ["Jakarta", "West Java", "East Java", "Central Java", "Banten", "North Sumatra", "South Sulawesi", "Bali", "Lampung", "Riau", "South Sumatra"] },
  { name: "Iran", code: "IR", phoneCode: "+98", states: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah"] },
  { name: "Iraq", code: "IQ", phoneCode: "+964", states: ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah", "Najaf", "Karbala", "Duhok"] },
  { name: "Ireland", code: "IE", phoneCode: "+353", states: ["Leinster", "Munster", "Connacht", "Ulster"] },
  { name: "Israel", code: "IL", phoneCode: "+972", states: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Beersheba", "Netanya"] },
  { name: "Italy", code: "IT", phoneCode: "+39", states: ["Lazio", "Lombardy", "Campania", "Sicily", "Veneto", "Piedmont", "Emilia-Romagna", "Tuscany", "Apulia", "Calabria", "Liguria", "Sardinia", "Abruzzo", "Marche"] },
  { name: "Ivory Coast", code: "CI", phoneCode: "+225", states: ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "San-Pédro", "Korhogo", "Man"] },
  { name: "Jamaica", code: "JM", phoneCode: "+1-876", states: ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "Mandeville", "May Pen"] },
  { name: "Japan", code: "JP", phoneCode: "+81", states: ["Tokyo", "Kanagawa", "Osaka", "Aichi", "Saitama", "Chiba", "Hyogo", "Hokkaido", "Fukuoka", "Shizuoka", "Ibaraki", "Kyoto", "Hiroshima"] },
  { name: "Jordan", code: "JO", phoneCode: "+962", states: ["Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba", "Madaba", "Jerash"] },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+7", states: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar"] },
  { name: "Kenya", code: "KE", phoneCode: "+254", states: ["Nairobi", "Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita-Taveta", "Garissa", "Wajir", "Mandera", "Marsabit", "Isiolo", "Meru", "Tharaka-Nithi", "Embu", "Kitui", "Machakos", "Makueni", "Nyandarua", "Nyeri", "Kirinyaga", "Murang'a", "Kiambu", "Turkana", "West Pokot", "Samburu", "Trans-Nzoia", "Uasin Gishu", "Elgeyo-Marakwet", "Nandi", "Baringo", "Laikipia", "Nakuru", "Narok", "Kajiado", "Kericho", "Bomet", "Kakamega", "Vihiga", "Bungoma", "Busia", "Siaya", "Kisumu", "Homa Bay", "Migori", "Kisii", "Nyamira"] },
  { name: "Kiribati", code: "KI", phoneCode: "+686", states: ["South Tarawa", "Betio", "Bikenibeu", "Teaoraereke"] },
  { name: "Kuwait", code: "KW", phoneCode: "+965", states: ["Kuwait City", "Hawalli", "Salmiya", "Sabah Al-Salem", "Al Jahra", "Ahmadi"] },
  { name: "Kyrgyzstan", code: "KG", phoneCode: "+996", states: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Uzgen"] },
  { name: "Laos", code: "LA", phoneCode: "+856", states: ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Thakhek", "Xam Neua"] },
  { name: "Latvia", code: "LV", phoneCode: "+371", states: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils"] },
  { name: "Lebanon", code: "LB", phoneCode: "+961", states: ["Beirut", "Tripoli", "Sidon", "Tyre", "Nabatieh", "Zahlé", "Baalbek"] },
  { name: "Lesotho", code: "LS", phoneCode: "+266", states: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Maputsoe"] },
  { name: "Liberia", code: "LR", phoneCode: "+231", states: ["Monrov ia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama"] },
  { name: "Libya", code: "LY", phoneCode: "+218", states: ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Ajdabiya"] },
  { name: "Liechtenstein", code: "LI", phoneCode: "+423", states: ["Vaduz", "Schaan", "Balz ers", "Triesen", "Eschen"] },
  { name: "Lithuania", code: "LT", phoneCode: "+370", states: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus"] },
  { name: "Luxembourg", code: "LU", phoneCode: "+352", states: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"] },
  { name: "Madagascar", code: "MG", phoneCode: "+261", states: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara"] },
  { name: "Malawi", code: "MW", phoneCode: "+265", states: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi"] },
  { name: "Malaysia", code: "MY", phoneCode: "+60", states: ["Selangor", "Johor", "Sabah", "Sarawak", "Perak", "Penang", "Pahang", "Kuala Lumpur", "Kedah", "Kelantan"] },
  { name: "Maldives", code: "MV", phoneCode: "+960", states: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo"] },
  { name: "Mali", code: "ML", phoneCode: "+223", states: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes"] },
  { name: "Malta", code: "MT", phoneCode: "+356", states: ["Valletta", "Birkirkara", "Mosta", "Qormi", "Żabbar", "Sliema"] },
  { name: "Marshall Islands", code: "MH", phoneCode: "+692", states: ["Majuro", "Ebeye", "Arno", "Jaluit", "Wotje"] },
  { name: "Mauritania", code: "MR", phoneCode: "+222", states: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérat"] },
  { name: "Mauritius", code: "MU", phoneCode: "+230", states: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet"] },
  { name: "Mexico", code: "MX", phoneCode: "+52", states: ["Mexico City", "Jalisco", "Nuevo León", "Puebla", "Guanajuato", "Chiapas", "Veracruz", "Baja California", "Michoacán", "Oaxaca", "Chihuahua", "Tamaulipas"] },
  { name: "Micronesia", code: "FM", phoneCode: "+691", states: ["Palikir", "Weno", "Kolonia", "Tofol", "Colonia"] },
  { name: "Moldova", code: "MD", phoneCode: "+373", states: ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul"] },
  { name: "Monaco", code: "MC", phoneCode: "+377", states: ["Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille"] },
  { name: "Mongolia", code: "MN", phoneCode: "+976", states: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Khovd"] },
  { name: "Montenegro", code: "ME", phoneCode: "+382", states: ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar"] },
  { name: "Morocco", code: "MA", phoneCode: "+212", states: ["Tanger-Tétouan-Al Hoceïma", "Oriental", "Fès-Meknès", "Rabat-Salé-Kénitra", "Béni Mellal-Khénifra", "Casablanca-Settat", "Marrakesh-Safi", "Drâa-Tafilalet", "Souss-Massa", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra", "Dakhla-Oued Ed-Dahab"] },
  { name: "Mozambique", code: "MZ", phoneCode: "+258", states: ["Maputo", "Matola", "Nampula", "Beira", "Chimoio", "Tete", "Quelimane"] },
  { name: "Myanmar", code: "MM", phoneCode: "+95", states: ["Yangon", "Mandalay", "Naypyidaw", "Bago", "Mawlamyine", "Pathein", "Monywa"] },
  { name: "Namibia", code: "NA", phoneCode: "+264", states: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund", "Katima Mulilo"] },
  { name: "Nauru", code: "NR", phoneCode: "+674", states: ["Yaren", "Denigomodu", "Aiwo", "Anabar", "Anibare"] },
  { name: "Nepal", code: "NP", phoneCode: "+977", states: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Birgunj", "Biratnagar", "Dharan"] },
  { name: "Netherlands", code: "NL", phoneCode: "+31", states: ["North Holland", "South Holland", "North Brabant", "Gelderland", "Utrecht", "Limburg", "Overijssel", "Groningen", "Friesland", "Drenthe", "Flevoland", "Zeeland"] },
  { name: "New Zealand", code: "NZ", phoneCode: "+64", states: ["Auckland", "Canterbury", "Wellington", "Waikato", "Bay of Plenty", "Otago", "Manawatu-Whanganui", "Hawke's Bay", "Taranaki"] },
  { name: "Nicaragua", code: "NI", phoneCode: "+505", states: ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Estelí", "Granada"] },
  { name: "Niger", code: "NE", phoneCode: "+227", states: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso"] },
  { name: "Nigeria", code: "NG", phoneCode: "+234", states: ["Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT (Abuja)", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"] },
  { name: "North Korea", code: "KP", phoneCode: "+850", states: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju"] },
  { name: "North Macedonia", code: "MK", phoneCode: "+389", states: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles"] },
  { name: "Norway", code: "NO", phoneCode: "+47", states: ["Oslo", "Vestland", "Viken", "Rogaland", "Trøndelag", "Innlandet", "Nordland", "Agder", "Møre og Romsdal", "Troms og Finnmark"] },
  { name: "Oman", code: "OM", phoneCode: "+968", states: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Ibri", "Buraimi"] },
  { name: "Pakistan", code: "PK", phoneCode: "+92", states: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Gilgit-Baltistan", "Azad Kashmir", "Islamabad Capital Territory"] },
  { name: "Palau", code: "PW", phoneCode: "+680", states: ["Ngerulmud", "Koror", "Melekeok", "Airai"] },
  { name: "Palestine", code: "PS", phoneCode: "+970", states: ["Gaza", "West Bank", "Ramallah", "Hebron", "Nablus", "Bethlehem"] },
  { name: "Panama", code: "PA", phoneCode: "+507", states: ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón"] },
  { name: "Papua New Guinea", code: "PG", phoneCode: "+675", states: ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Madang", "Wewak"] },
  { name: "Paraguay", code: "PY", phoneCode: "+595", states: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré"] },
  { name: "Peru", code: "PE", phoneCode: "+51", states: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo"] },
  { name: "Philippines", code: "PH", phoneCode: "+63", states: ["Metro Manila", "Calabarzon", "Central Luzon", "Western Visayas", "Central Visayas", "Davao Region", "Ilocos Region", "Soccsksargen"] },
  { name: "Poland", code: "PL", phoneCode: "+48", states: ["Masovian", "Silesian", "Greater Poland", "Lesser Poland", "Lower Silesian", "Łódź", "Pomeranian", "Kuyavian-Pomeranian"] },
  { name: "Portugal", code: "PT", phoneCode: "+351", states: ["Lisbon", "Porto", "Faro", "Setúbal", "Braga", "Coimbra", "Aveiro", "Madeira", "Azores"] },
  { name: "Qatar", code: "QA", phoneCode: "+974", states: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor", "Al Shamal"] },
  { name: "Romania", code: "RO", phoneCode: "+40", states: ["Bucharest", "Cluj", "Timiș", "Iași", "Constanța", "Brașov", "Prahova", "Dolj"] },
  { name: "Russia", code: "RU", phoneCode: "+7", states: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod", "Kazan", "Chelyabinsk", "Omsk", "Samara", "Rostov-on-Don", "Ufa", "Krasnoyarsk"] },
  { name: "Rwanda", code: "RW", phoneCode: "+250", states: ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba"] },
  { name: "Saint Kitts and Nevis", code: "KN", phoneCode: "+1-869", states: ["Basseterre", "Charlestown", "Dieppe Bay Town"] },
  { name: "Saint Lucia", code: "LC", phoneCode: "+1-758", states: ["Castries", "Vieux Fort", "Micoud", "Soufrière", "Gros Islet"] },
  { name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+1-784", states: ["Kingstown", "Georgetown", "Biabou", "Barrouallie"] },
  { name: "Samoa", code: "WS", phoneCode: "+685", states: ["Apia", "Vaitele", "Faleula", "Siusega"] },
  { name: "San Marino", code: "SM", phoneCode: "+378", states: ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"] },
  { name: "Sao Tome and Principe", code: "ST", phoneCode: "+239", states: ["São Tomé", "Trindade", "Neves", "Santana"] },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+966", states: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Tabuk", "Khobar", "Abha"] },
  { name: "Senegal", code: "SN", phoneCode: "+221", states: ["Dakar", "Touba", "Thiès", "Kaolack", "Saint-Louis", "Ziguinchor", "Mbour"] },
  { name: "Serbia", code: "RS", phoneCode: "+381", states: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Pristina"] },
  { name: "Seychelles", code: "SC", phoneCode: "+248", states: ["Victoria", "Anse Boileau", "Beau Vallon", "Cascade"] },
  { name: "Sierra Leone", code: "SL", phoneCode: "+232", states: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"] },
  { name: "Singapore", code: "SG", phoneCode: "+65", states: ["Central", "North", "North-East", "East", "West"] },
  { name: "Slovakia", code: "SK", phoneCode: "+421", states: ["Bratislava", "Košice", "Prešov", "Žilina", "Banská Bystrica", "Nitra"] },
  { name: "Slovenia", code: "SI", phoneCode: "+386", states: ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper"] },
  { name: "Solomon Islands", code: "SB", phoneCode: "+677", states: ["Honiara", "Auki", "Gizo", "Buala"] },
  { name: "Somalia", code: "SO", phoneCode: "+252", states: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Merca", "Berbera"] },
  { name: "South Africa", code: "ZA", phoneCode: "+27", states: ["Gauteng", "KwaZulu-Natal", "Western Cape", "Eastern Cape", "Limpopo", "Mpumalanga", "North West", "Free State", "Northern Cape"] },
  { name: "South Korea", code: "KR", phoneCode: "+82", states: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Gyeonggi", "Gangwon", "North Chungcheong", "South Chungcheong", "North Jeolla", "South Jeolla", "North Gyeongsang", "South Gyeongsang", "Jeju"] },
  { name: "South Sudan", code: "SS", phoneCode: "+211", states: ["Juba", "Malakal", "Wau", "Yei", "Yambio", "Bor"] },
  { name: "Spain", code: "ES", phoneCode: "+34", states: ["Madrid", "Catalonia", "Andalusia", "Valencia", "Galicia", "Castile and León", "Basque Country", "Canary Islands", "Castilla-La Mancha", "Murcia", "Aragon", "Balearic Islands", "Extremadura", "Asturias", "Navarre", "Cantabria", "La Rioja"] },
  { name: "Sri Lanka", code: "LK", phoneCode: "+94", states: ["Western", "Central", "Southern", "Northern", "Eastern", "North Western", "North Central", "Uva", "Sabaragamuwa"] },
  { name: "Sudan", code: "SD", phoneCode: "+249", states: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Kosti", "El Obeid"] },
  { name: "Suriname", code: "SR", phoneCode: "+597", states: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"] },
  { name: "Sweden", code: "SE", phoneCode: "+46", states: ["Stockholm", "Västra Götaland", "Skåne", "Uppsala", "Östergötland", "Halland", "Södermanland"] },
  { name: "Switzerland", code: "CH", phoneCode: "+41", states: ["Zürich", "Bern", "Vaud", "Aargau", "Geneva", "Lucerne", "Ticino", "Valais"] },
  { name: "Syria", code: "SY", phoneCode: "+963", states: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor"] },
  { name: "Taiwan", code: "TW", phoneCode: "+886", states: ["Taipei", "New Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan"] },
  { name: "Tajikistan", code: "TJ", phoneCode: "+992", states: ["Dushanbe", "Khujand", "Bokhtar", "Kulob", "Istaravshan"] },
  { name: "Tanzania", code: "TZ", phoneCode: "+255", states: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Zanzibar"] },
  { name: "Thailand", code: "TH", phoneCode: "+66", states: ["Bangkok", "Chiang Mai", "Nonthaburi", "Nakhon Ratchasima", "Chiang Rai", "Udon Thani", "Surat Thani", "Khon Kaen"] },
  { name: "Timor-Leste", code: "TL", phoneCode: "+670", states: ["Dili", "Baucau", "Maliana", "Suai", "Lospalos"] },
  { name: "Togo", code: "TG", phoneCode: "+228", states: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Dapaong"] },
  { name: "Tonga", code: "TO", phoneCode: "+676", states: ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini"] },
  { name: "Trinidad and Tobago", code: "TT", phoneCode: "+1-868", states: ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin"] },
  { name: "Tunisia", code: "TN", phoneCode: "+216", states: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès"] },
  { name: "Turkey", code: "TR", phoneCode: "+90", states: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya"] },
  { name: "Turkmenistan", code: "TM", phoneCode: "+993", states: ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat"] },
  { name: "Tuvalu", code: "TV", phoneCode: "+688", states: ["Funafuti", "Vaiaku", "Alapi"] },
  { name: "Uganda", code: "UG", phoneCode: "+256", states: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera", "Mbale", "Mukono", "Entebbe"] },
  { name: "Ukraine", code: "UA", phoneCode: "+380", states: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih"] },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971", states: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"] },
  { name: "United Kingdom", code: "GB", phoneCode: "+44", states: ["England", "Scotland", "Wales", "Northern Ireland"] },
  { name: "United States", code: "US", phoneCode: "+1", states: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"] },
  { name: "Uruguay", code: "UY", phoneCode: "+598", states: ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera", "Maldonado"] },
  { name: "Uzbekistan", code: "UZ", phoneCode: "+998", states: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara", "Fergana", "Nukus"] },
  { name: "Vanuatu", code: "VU", phoneCode: "+678", states: ["Port Vila", "Luganville", "Norsup", "Isangel"] },
  { name: "Vatican City", code: "VA", phoneCode: "+39", states: ["Vatican City"] },
  { name: "Venezuela", code: "VE", phoneCode: "+58", states: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana"] },
  { name: "Vietnam", code: "VN", phoneCode: "+84", states: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang"] },
  { name: "Yemen", code: "YE", phoneCode: "+967", states: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Dhamar"] },
  { name: "Zambia", code: "ZM", phoneCode: "+260", states: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone"] },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+263", states: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth", "Kwekwe", "Kadoma"] }
];

export const getCountryByCode = (code: string) => {
  return countries.find(c => c.code === code);
};

export const getCountryByName = (name: string) => {
  return countries.find(c => c.name === name);
};

// ─── Pricing Model Classification ───────────────────────────────────────────
// Determines how workers in a country typically price their services.

/** Countries where workers are commonly billed at an hourly rate */
export const HOURLY_PRICING_COUNTRIES = new Set([
  'United States', 'Canada', 'United Kingdom', 'Australia', 'New Zealand', 'Ireland',
  'Germany', 'France', 'Netherlands', 'Belgium', 'Switzerland', 'Austria', 'Sweden',
  'Norway', 'Denmark', 'Finland', 'Luxembourg', 'Iceland', 'Liechtenstein', 'Monaco',
  'Andorra', 'San Marino', 'Vatican City',
  'Spain', 'Italy', 'Portugal', 'Greece', 'Cyprus', 'Malta',
  'Poland', 'Czech Republic', 'Slovakia', 'Hungary', 'Romania', 'Bulgaria',
  'Croatia', 'Slovenia', 'Estonia', 'Latvia', 'Lithuania',
  'Israel', 'Singapore', 'Japan', 'South Korea', 'Taiwan', 'Brunei',
  'United Arab Emirates', 'Qatar', 'Kuwait', 'Bahrain', 'Saudi Arabia', 'Oman',
]);

/** Countries where workers are commonly billed at a daily rate (not hourly) */
export const DAILY_PRICING_COUNTRIES = new Set([
  'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan',
  'Philippines', 'Indonesia', 'Vietnam', 'Thailand', 'Malaysia', 'Myanmar',
  'Cambodia', 'Laos', 'Timor-Leste', 'Mongolia',
  'China',
  'Egypt', 'Jordan', 'Morocco', 'Tunisia', 'Algeria', 'Libya', 'Sudan',
  'Palestine', 'Lebanon', 'Iraq', 'Iran', 'Syria', 'Yemen',
  'Turkey', 'Russia', 'Ukraine', 'Georgia', 'Armenia', 'Azerbaijan',
  'Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Uzbekistan', 'Turkmenistan',
  'Moldova', 'Belarus', 'Serbia', 'Bosnia and Herzegovina',
  'North Macedonia', 'Montenegro', 'Kosovo', 'Albania',
  'Mexico', 'Brazil', 'Colombia', 'Argentina', 'Chile', 'Peru', 'Venezuela',
  'Bolivia', 'Ecuador', 'Paraguay', 'Uruguay', 'Guyana', 'Suriname',
  'Costa Rica', 'Panama', 'Guatemala', 'Honduras', 'El Salvador', 'Nicaragua',
  'Dominican Republic', 'Jamaica', 'Trinidad and Tobago', 'Haiti', 'Cuba',
  // Africa - per day/per month pricing is standard
  'Nigeria', 'South Africa', 'Kenya', 'Tanzania', 'Uganda', 'Rwanda', 'Ethiopia',
  'Ghana', 'Zimbabwe', 'Zambia', 'Mozambique', 'Namibia', 'Botswana',
  'Malawi', 'Madagascar', 'Mauritius', 'Seychelles',
  'Cameroon', 'Ivory Coast', 'Senegal', 'Mali', 'Burkina Faso', 'Niger',
  'Togo', 'Benin', 'Guinea-Bissau', 'Guinea', 'Chad', 'Gabon',
  'Congo (Republic)', 'Congo (DRC)', 'Equatorial Guinea', 'Central African Republic',
  'Angola', 'Liberia', 'Sierra Leone', 'Gambia', 'Eswatini', 'Lesotho',
  'Djibouti', 'Eritrea', 'Somalia', 'Comoros', 'Cape Verde', 'Burundi',
]);

/** All other countries default to fully negotiable pricing */

export type PricingModel = 'hourly' | 'daily' | 'negotiable';

/**
 * Returns the dominant pricing convention for a country.
 *   'hourly'     → show chargeHourly on cards; form shows hourly field
 *   'daily'      → hide per-hour; form shows daily field + negotiable toggle
 *   'negotiable' → always show "Amount: Not fixed" on cards; form shows negotiable only
 */
export function getPricingModel(countryName: string): PricingModel {
  if (HOURLY_PRICING_COUNTRIES.has(countryName)) return 'hourly';
  if (DAILY_PRICING_COUNTRIES.has(countryName)) return 'daily';
  return 'negotiable';
}

// ─── Country Currency Data ────────────────────────────────────────────────────

export interface CountryCurrency {
  /** ISO 4217 currency code e.g. 'NGN', 'USD', 'GBP' */
  code: string;
  /** Display symbol e.g. '₦', '$', '£' */
  symbol: string;
  /**
   * Approximate rate: 1 USD = this many local currency units.
   * Used for display conversion only — actual settlement is handled by the gateway.
   */
  usdRate: number;
}

/** Map of country name → currency. Defaults to USD for unknown countries. */
export const COUNTRY_CURRENCY: Record<string, CountryCurrency> = {
  // ── Africa ──
  'Nigeria':                  { code: 'NGN',  symbol: '₦',     usdRate: 1600   },
  'Ghana':                    { code: 'GHS',  symbol: 'GH₵',   usdRate: 15     },
  'South Africa':             { code: 'ZAR',  symbol: 'R',     usdRate: 19     },
  'Kenya':                    { code: 'KES',  symbol: 'KSh',   usdRate: 130    },
  'Egypt':                    { code: 'EGP',  symbol: 'E£',    usdRate: 49     },
  'Rwanda':                   { code: 'RWF',  symbol: 'RF',    usdRate: 1350   },
  'Tanzania':                 { code: 'TZS',  symbol: 'TSh',   usdRate: 2600   },
  'Uganda':                   { code: 'UGX',  symbol: 'USh',   usdRate: 3750   },
  'Zambia':                   { code: 'ZMW',  symbol: 'ZK',    usdRate: 27     },
  'Mozambique':               { code: 'MZN',  symbol: 'MT',    usdRate: 64     },
  'Ethiopia':                 { code: 'ETB',  symbol: 'Br',    usdRate: 123    },
  'Ivory Coast':              { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Senegal':                  { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Cameroon':                 { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Mali':                     { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Burkina Faso':             { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Niger':                    { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Togo':                     { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Benin':                    { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Guinea-Bissau':            { code: 'XOF',  symbol: 'CFA',   usdRate: 605    },
  'Guinea':                   { code: 'GNF',  symbol: 'FG',    usdRate: 8600   },
  'Chad':                     { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Gabon':                    { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Congo (Republic)':         { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Equatorial Guinea':        { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Central African Republic': { code: 'XAF',  symbol: 'FCFA',  usdRate: 605    },
  'Congo (DRC)':              { code: 'CDF',  symbol: 'FC',    usdRate: 2800   },
  'Angola':                   { code: 'AOA',  symbol: 'Kz',    usdRate: 880    },
  'Namibia':                  { code: 'NAD',  symbol: 'N$',    usdRate: 19     },
  'Botswana':                 { code: 'BWP',  symbol: 'P',     usdRate: 14     },
  'Zimbabwe':                 { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Malawi':                   { code: 'MWK',  symbol: 'MK',    usdRate: 1750   },
  'Madagascar':               { code: 'MGA',  symbol: 'Ar',    usdRate: 4500   },
  'Mauritius':                { code: 'MUR',  symbol: '₨',     usdRate: 46     },
  'Seychelles':               { code: 'SCR',  symbol: '₨',     usdRate: 14     },
  'Morocco':                  { code: 'MAD',  symbol: 'DH',    usdRate: 10     },
  'Algeria':                  { code: 'DZD',  symbol: 'DA',    usdRate: 135    },
  'Tunisia':                  { code: 'TND',  symbol: 'DT',    usdRate: 3.1    },
  'Libya':                    { code: 'LYD',  symbol: 'LD',    usdRate: 4.9    },
  'Sudan':                    { code: 'SDG',  symbol: 'SDG',   usdRate: 600    },
  'South Sudan':              { code: 'SSP',  symbol: 'SSP',   usdRate: 1300   },
  'Somalia':                  { code: 'SOS',  symbol: 'Sh',    usdRate: 571    },
  'Gambia':                   { code: 'GMD',  symbol: 'D',     usdRate: 71     },
  'Sierra Leone':             { code: 'SLE',  symbol: 'Le',    usdRate: 22     },
  'Liberia':                  { code: 'LRD',  symbol: 'L$',    usdRate: 191    },
  'Cape Verde':               { code: 'CVE',  symbol: 'Esc',   usdRate: 100    },
  'Djibouti':                 { code: 'DJF',  symbol: 'Fdj',   usdRate: 178    },
  'Eritrea':                  { code: 'ERN',  symbol: 'Nfk',   usdRate: 15     },
  'Comoros':                  { code: 'KMF',  symbol: 'CF',    usdRate: 450    },
  'Sao Tome and Principe':    { code: 'STN',  symbol: 'Db',    usdRate: 22     },
  'Eswatini':                 { code: 'SZL',  symbol: 'L',     usdRate: 19     },
  'Lesotho':                  { code: 'LSL',  symbol: 'L',     usdRate: 19     },
  'Burundi':                  { code: 'BIF',  symbol: 'Fr',    usdRate: 2900   },
  // ── Americas ──
  'United States':            { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Canada':                   { code: 'CAD',  symbol: 'CA$',   usdRate: 1.36   },
  'Mexico':                   { code: 'MXN',  symbol: 'MX$',   usdRate: 17     },
  'Brazil':                   { code: 'BRL',  symbol: 'R$',    usdRate: 5.1    },
  'Argentina':                { code: 'ARS',  symbol: 'AR$',   usdRate: 950    },
  'Colombia':                 { code: 'COP',  symbol: 'CO$',   usdRate: 3900   },
  'Chile':                    { code: 'CLP',  symbol: 'CL$',   usdRate: 930    },
  'Peru':                     { code: 'PEN',  symbol: 'S/',    usdRate: 3.8    },
  'Venezuela':                { code: 'VES',  symbol: 'Bs.',   usdRate: 36     },
  'Ecuador':                  { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Bolivia':                  { code: 'BOB',  symbol: 'Bs',    usdRate: 6.9    },
  'Paraguay':                 { code: 'PYG',  symbol: '₲',     usdRate: 7300   },
  'Uruguay':                  { code: 'UYU',  symbol: '$U',    usdRate: 39     },
  'Guyana':                   { code: 'GYD',  symbol: 'G$',    usdRate: 209    },
  'Suriname':                 { code: 'SRD',  symbol: 'Sr$',   usdRate: 33     },
  'Jamaica':                  { code: 'JMD',  symbol: 'J$',    usdRate: 157    },
  'Trinidad and Tobago':      { code: 'TTD',  symbol: 'TT$',   usdRate: 6.8    },
  'Cuba':                     { code: 'CUP',  symbol: '$',     usdRate: 24     },
  'Dominican Republic':       { code: 'DOP',  symbol: 'RD$',   usdRate: 59     },
  'Haiti':                    { code: 'HTG',  symbol: 'G',     usdRate: 131    },
  'Guatemala':                { code: 'GTQ',  symbol: 'Q',     usdRate: 7.8    },
  'Honduras':                 { code: 'HNL',  symbol: 'L',     usdRate: 25     },
  'El Salvador':              { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Nicaragua':                { code: 'NIO',  symbol: 'C$',    usdRate: 37     },
  'Costa Rica':               { code: 'CRC',  symbol: '₡',     usdRate: 520    },
  'Panama':                   { code: 'USD',  symbol: '$',     usdRate: 1      },
  // ── Europe ──
  'United Kingdom':           { code: 'GBP',  symbol: '£',     usdRate: 0.79   },
  'Germany':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'France':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Italy':                    { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Spain':                    { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Netherlands':              { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Belgium':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Switzerland':              { code: 'CHF',  symbol: 'CHF',   usdRate: 0.9    },
  'Austria':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Sweden':                   { code: 'SEK',  symbol: 'kr',    usdRate: 10.5   },
  'Norway':                   { code: 'NOK',  symbol: 'kr',    usdRate: 10.6   },
  'Denmark':                  { code: 'DKK',  symbol: 'kr',    usdRate: 6.9    },
  'Finland':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Iceland':                  { code: 'ISK',  symbol: 'kr',    usdRate: 139    },
  'Ireland':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Luxembourg':               { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Portugal':                 { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Greece':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Malta':                    { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Cyprus':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Poland':                   { code: 'PLN',  symbol: 'zł',    usdRate: 4.0    },
  'Czech Republic':           { code: 'CZK',  symbol: 'Kč',    usdRate: 23     },
  'Hungary':                  { code: 'HUF',  symbol: 'Ft',    usdRate: 360    },
  'Romania':                  { code: 'RON',  symbol: 'lei',   usdRate: 4.6    },
  'Bulgaria':                 { code: 'BGN',  symbol: 'лв',    usdRate: 1.8    },
  'Croatia':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Slovakia':                 { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Slovenia':                 { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Estonia':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Latvia':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Lithuania':                { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Russia':                   { code: 'RUB',  symbol: '₽',     usdRate: 90     },
  'Ukraine':                  { code: 'UAH',  symbol: '₴',     usdRate: 40     },
  'Turkey':                   { code: 'TRY',  symbol: '₺',     usdRate: 33     },
  'Serbia':                   { code: 'RSD',  symbol: 'din',   usdRate: 108    },
  'Bosnia and Herzegovina':   { code: 'BAM',  symbol: 'KM',    usdRate: 1.8    },
  'North Macedonia':          { code: 'MKD',  symbol: 'ден',   usdRate: 57     },
  'Montenegro':               { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Albania':                  { code: 'ALL',  symbol: 'L',     usdRate: 97     },
  'Kosovo':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Moldova':                  { code: 'MDL',  symbol: 'L',     usdRate: 18     },
  'Belarus':                  { code: 'BYN',  symbol: 'Br',    usdRate: 3.3    },
  'Georgia':                  { code: 'GEL',  symbol: '₾',     usdRate: 2.7    },
  'Armenia':                  { code: 'AMD',  symbol: '֏',     usdRate: 400    },
  'Azerbaijan':               { code: 'AZN',  symbol: '₼',     usdRate: 1.7    },
  'Liechtenstein':            { code: 'CHF',  symbol: 'CHF',   usdRate: 0.9    },
  'Monaco':                   { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Andorra':                  { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'San Marino':               { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  'Vatican City':             { code: 'EUR',  symbol: '€',     usdRate: 0.92   },
  // ── Asia ──
  'Japan':                    { code: 'JPY',  symbol: '¥',     usdRate: 150    },
  'China':                    { code: 'CNY',  symbol: '¥',     usdRate: 7.2    },
  'India':                    { code: 'INR',  symbol: '₹',     usdRate: 84     },
  'South Korea':              { code: 'KRW',  symbol: '₩',     usdRate: 1340   },
  'Indonesia':                { code: 'IDR',  symbol: 'Rp',    usdRate: 15700  },
  'Malaysia':                 { code: 'MYR',  symbol: 'RM',    usdRate: 4.7    },
  'Philippines':              { code: 'PHP',  symbol: '₱',     usdRate: 58     },
  'Thailand':                 { code: 'THB',  symbol: '฿',     usdRate: 36     },
  'Vietnam':                  { code: 'VND',  symbol: '₫',     usdRate: 25000  },
  'Bangladesh':               { code: 'BDT',  symbol: '৳',     usdRate: 110    },
  'Pakistan':                 { code: 'PKR',  symbol: '₨',     usdRate: 280    },
  'Sri Lanka':                { code: 'LKR',  symbol: 'Rs',    usdRate: 320    },
  'Nepal':                    { code: 'NPR',  symbol: 'Rs',    usdRate: 134    },
  'Myanmar':                  { code: 'MMK',  symbol: 'K',     usdRate: 2100   },
  'Cambodia':                 { code: 'KHR',  symbol: '₭',     usdRate: 4100   },
  'Laos':                     { code: 'LAK',  symbol: '₭',     usdRate: 21000  },
  'Singapore':                { code: 'SGD',  symbol: 'S$',    usdRate: 1.34   },
  'Taiwan':                   { code: 'TWD',  symbol: 'NT$',   usdRate: 32     },
  'Brunei':                   { code: 'BND',  symbol: 'B$',    usdRate: 1.34   },
  'Mongolia':                 { code: 'MNT',  symbol: '₮',     usdRate: 3400   },
  'Timor-Leste':              { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Saudi Arabia':             { code: 'SAR',  symbol: 'SR',    usdRate: 3.75   },
  'United Arab Emirates':     { code: 'AED',  symbol: 'AED',   usdRate: 3.67   },
  'Qatar':                    { code: 'QAR',  symbol: 'QR',    usdRate: 3.64   },
  'Kuwait':                   { code: 'KWD',  symbol: 'KD',    usdRate: 0.31   },
  'Bahrain':                  { code: 'BHD',  symbol: 'BD',    usdRate: 0.38   },
  'Oman':                     { code: 'OMR',  symbol: 'OMR',   usdRate: 0.38   },
  'Jordan':                   { code: 'JOD',  symbol: 'JD',    usdRate: 0.71   },
  'Lebanon':                  { code: 'USD',  symbol: '$',     usdRate: 1      },
  'Israel':                   { code: 'ILS',  symbol: '₪',     usdRate: 3.7    },
  'Iran':                     { code: 'IRR',  symbol: 'Rl',    usdRate: 42000  },
  'Iraq':                     { code: 'IQD',  symbol: 'IQD',   usdRate: 1310   },
  'Syria':                    { code: 'SYP',  symbol: '£',     usdRate: 13000  },
  'Yemen':                    { code: 'YER',  symbol: 'Rl',    usdRate: 250    },
  'Palestine':                { code: 'ILS',  symbol: '₪',     usdRate: 3.7    },
  'Afghanistan':              { code: 'AFN',  symbol: '؋',     usdRate: 70     },
  'Kazakhstan':               { code: 'KZT',  symbol: '₸',     usdRate: 460    },
  'Uzbekistan':               { code: 'UZS',  symbol: "so'm",  usdRate: 12600  },
  'Kyrgyzstan':               { code: 'KGS',  symbol: 'с',     usdRate: 89     },
  'Tajikistan':               { code: 'TJS',  symbol: 'SM',    usdRate: 10.9   },
  'Turkmenistan':             { code: 'TMT',  symbol: 'T',     usdRate: 3.5    },
  // ── Oceania ──
  'Australia':                { code: 'AUD',  symbol: 'A$',    usdRate: 1.56   },
  'New Zealand':              { code: 'NZD',  symbol: 'NZ$',   usdRate: 1.63   },
  'Papua New Guinea':         { code: 'PGK',  symbol: 'K',     usdRate: 3.8    },
  'Fiji':                     { code: 'FJD',  symbol: 'FJ$',   usdRate: 2.26   },
};

/**
 * Returns the currency for a country, defaulting to USD for unknown countries.
 */
export function getCountryCurrency(countryName: string): CountryCurrency {
  return COUNTRY_CURRENCY[countryName] || { code: 'USD', symbol: '$', usdRate: 1 };
}

/**
 * Format a subscription plan price for display in the user's local currency.
 * @param planAmount   The amount as stored on the plan object.
 * @param planCurrency 'NGN' (Nigeria plans) or 'USD' (Africa/Global plans). Omit = NGN.
 * @param userCountry  The user's country name.
 */
export function formatSubscriptionPrice(
  planAmount: number,
  planCurrency: string = 'NGN',
  userCountry: string
): string {
  if (planAmount === 0) return 'Free';
  const currency = getCountryCurrency(userCountry);
  if (planCurrency === 'NGN') {
    // Nigeria plan: amount already in NGN; show with NGN symbol
    return `${currency.symbol}${planAmount.toLocaleString()}`;
  }
  // USD plan: convert to local currency for display
  const localAmount = Math.round(planAmount * currency.usdRate);
  return `${currency.symbol}${localAmount.toLocaleString()}`;
}

/**
 * Convert a plan amount to local currency units for payment.
 * Returns the amount the gateway should charge.
 */
export function getLocalPaymentAmount(
  planAmount: number,
  planCurrency: string = 'NGN',
  userCountry: string
): number {
  if (planCurrency === 'NGN') return planAmount;
  const currency = getCountryCurrency(userCountry);
  return Math.round(planAmount * currency.usdRate);
}
