
export const NIGERIA_LOCATIONS = [
    { name: 'Abia', towns: ['Umuahia', 'Aba', 'Ohafia', 'Arochukwu', 'Bende', 'Isuikwuato'] },
    { name: 'Adamawa', towns: ['Yola', 'Mubi', 'Jimeta', 'Ganye', 'Numan', 'Michika'] },
    { name: 'Akwa Ibom', towns: ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak', 'Etinan'] },
    { name: 'Anambra', towns: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Ihiala', 'Otuocha'] },
    { name: 'Bauchi', towns: ['Bauchi', 'Azare', 'Misau', 'Jama’are', 'Katagum', 'Toro'] },
    { name: 'Bayelsa', towns: ['Yenagoa', 'Ogbia', 'Nembe', 'Brass', 'Sagbama', 'Kaiama'] },
    { name: 'Benue', towns: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Zaki Biam', 'Adikpo'] },
    { name: 'Borno', towns: ['Maiduguri', 'Biu', 'Monguno', 'Bama', 'Dikwa', 'Chibok'] },
    { name: 'Cross River', towns: ['Calabar', 'Ikom', 'Obudu', 'Ogoja', 'Akamkpa', 'Ugep'] },
    { name: 'Delta', towns: ['Asaba', 'Warri', 'Ughelli', 'Sapele', 'Agbor', 'Oleh', 'Ogwashi-Uku'] },
    { name: 'Ebonyi', towns: ['Abakaliki', 'Afikpo', 'Onueke', 'Ikwo', 'Ezza', 'Ohaozara'] },
    { name: 'Edo', towns: ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Agenebode', 'Irrua'] },
    { name: 'Ekiti', towns: ['Ado-Ekiti', 'Ikere', 'Ijero', 'Ikole', 'Omuo', 'Aramoko'] },
    { name: 'Enugu', towns: ['Enugu', 'Nsukka', 'Agbani', 'Oji River', 'Udi', 'Awgu'] },
    { name: 'Federal Capital Territory', towns: ['Maitama', 'Asokoro', 'Garki', 'Wuse', 'Life Camp', 'Apo', 'Gwarimpa', 'Katampe', 'Jahi', 'Lugbe', 'Kubwa', 'Gwagwalada', 'Bwari', 'Kuje', 'Kwali', 'Abaji'] },
    { name: 'Gombe', towns: ['Gombe', 'Kaltungo', 'Billiri', 'Dukku', 'Yamaltu-Deba', 'Funakaye'] },
    { name: 'Imo', towns: ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta', 'Mbano'] },
    { name: 'Jigawa', towns: ['Dutse', 'Hadejia', 'Gumel', 'Kazaure', 'Birnin Kudu', 'Ringim'] },
    { name: 'Kaduna', towns: ['Kaduna', 'Zaria', 'Kafanchan', 'Soba', 'Birnin Gwari', 'Kagoro'] },
    { name: 'Kano', towns: ['Kano', 'Wudil', 'Rano', 'Gwarzo', 'Gaya', 'Bichi'] },
    { name: 'Katsina', towns: ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma', 'Kankia'] },
    { name: 'Kebbi', towns: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega', 'Bagudo'] },
    { name: 'Kogi', towns: ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa', 'Dekina'] },
    { name: 'Kwara', towns: ['Ilorin', 'Offa', 'Jebba', 'Omu-Aran', 'Lafiagi', 'Kaiama'] },
    { name: 'Lagos', towns: ['Ikeja', 'Lagos Island', 'Epe', 'Ikorodu', 'Badagry', 'Victoria Island'] },
    { name: 'Nasarawa', towns: ['Lafia', 'Keffi', 'Akwanga', 'Karu', 'Toto', 'Doma', 'Mararaba'] },
    { name: 'Niger', towns: ['Minna', 'Bida', 'Kontagora', 'Suleja', 'Mokwa', 'New Bussa'] },
    { name: 'Ogun', towns: ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ota', 'Ilaro', 'Ago-Iwoye'] },
    { name: 'Ondo', towns: ['Akure', 'Owo', 'Ikare', 'Ondo', 'Okitipupa', 'Idanre'] },
    { name: 'Osun', towns: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Ikirun', 'Ila-Orangun'] },
    { name: 'Oyo', towns: ['Ibadan', 'Ogbomoso', 'Iseyin', 'Saki', 'Eruwa', 'Oyo Town'] },
    { name: 'Plateau', towns: ['Jos', 'Barkin Ladi', 'Pankshin', 'Langtang', 'Shendam', 'Riyom'] },
    { name: 'Rivers', towns: ['Port Harcourt', 'Bonny', 'Omoku', 'Ahoada', 'Okrika', 'Degema'] },
    { name: 'Sokoto', towns: ['Sokoto', 'Wurno', 'Tambuwal', 'Gwadabawa', 'Illela', 'Binji'] },
    { name: 'Taraba', towns: ['Jalingo', 'Wukari', 'Takum', 'Bali', 'Gembu', 'Lau'] },
    { name: 'Yobe', towns: ['Damaturu', 'Potiskum', 'Nguru', 'Gashua', 'Geidam', 'Buni Yadi'] },
    { name: 'Zamfara', towns: ['Gusau', 'Kaura Namoda', 'Anka', 'Talata Mafara', 'Maru', 'Tsafe'] },
];
